version: '3'

services:
    db:
        image: redis
    app:
        image: streampush/streampush
        build: ./app/
        volumes:
            - ./spdata:/opt/streampush/data
        depends_on:
            - relay
            - db
        ports:
            - "8000:8000"
        environment:
            - DJANGO_SECRET=ThisIsABadSecret
    relay:
        image: streampush/relay
        build: ./relay-server/
        volumes:
            - ./spdata:/opt/streampush/data
        ports:
            - "1935:1935"
