version: '3'

services:
    db:
        image: redis
    app:
        image: streampush/streampush
        volumes:
            - ./spdata:/opt/streampush/data
        depends_on:
            - relay
            - db
        ports:
            - 80:8000
        environment:
            - DJANGO_SECRET=5bR1IQgLmgntbYcJi2lORrua6gSpOtHCAOqCNVg7ZlLwCKeuzK5IIBbrKObwvbi9WY8zbpzJufGh0CK0WD7OAzvIQ2THxqkhjyTE0Lcgduo0tlacQALnN8vC9tDr1KDv
    relay:
        image: streampush/relay
        volumes:
            - ./spdata:/opt/streampush/data
        ports:
            - 1935:1935
